name: meals
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1 
  transparent_image: ^2.0.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
